# Используем официальный образ Ubuntu 18.04 как базовый
FROM ubuntu:22.04

# Устанавливаем временную зону (Москва) чтобы избежать запросов при установке пакетов
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Обновляем пакеты и устанавливаем необходимые зависимости:
# - build-essential: компилятор GCC, make и другие базовые инструменты сборки
# - qt5-default: базовые компоненты Qt5 (включает qmake)
# - qtcreator: IDE для разработки (опционально, можно удалить для production)
# - git: система контроля версий
# - cmake: альтернативная система сборки
# После установки очищаем кеш apt для уменьшения размера образа
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    qt6-base-dev \
    qt6-tools-dev-tools \
    qt6-l10n-tools \
    libqt6sql6-sqlite \
    && rm -rf /var/lib/apt/lists/*

# Создаем рабочую директорию в /usr/src/app (стандартный путь для приложений)
WORKDIR /usr/src/app

# Копируем все файлы из текущей директории в контейнер
# Включая исходный код сервера и .pro файл
COPY . .

# Удаляем старую директорию build (если есть) и создаем новую
RUN rm -rf build && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make

# Открываем порт, который будет использовать сервер
EXPOSE 33333 33334

# Указываем команду для запуска сервера при старте контейнера
CMD ["./build/server"]



# Запуск сервера
# Docker build -t echo-server .
# docker run -it -p 33333:33333 -p 33334:33334 qt-server
